### ISSUE TITLE
Silence the logger when running rails console or when running tests

### ISSUE THREAD

**Issue by kamal** [splitio/ruby-client#151]
By default, the SDK logs out to STDOUT. This can be very distracting and noisy when a developer starts a rails console session or when running tests. The SDK should detect these run modes and configure the default logger to be silent, or redirect to the Rails logger instead of STDOUT.

Here's a snippet of what I do in my split configuration.

```
options = {}
options[:logger] = NullObject.new if defined?(Rails::Console) || Rails.env.test?
...
SplitIoClient::SplitFactory.new(api_key, options)
```

Note: It's unfortunately that I have to explicitly pass in a `NullObject` which is not standard in Ruby. Perhaps the options parser should distinguish between passing in an explicit `nil` vs not configuring the value.

**Comment by patricioe** [comment]
@maksimf let's discuss.

Thanks @kamal

**Comment by maksimf** [comment]
Thank you for this, I think the suggestion makes sense and we can definitely go this way

**Comment by maksimf** [comment]
@kamal done!
