### ISSUE TITLE
Gem Namespace & Directory Practice

### ISSUE THREAD

**Issue by metaskills** [splitio/ruby-client#157]
Congrats, this gem looks really nice and I'm really looking forward to using this it with the Split.io service. 

While doing a technical review, I noticed that the gem has several namespace issues. These appear to be simple fixes but wanted your thoughts before doing a pull request. 

### General Directory & Namespace

Below are some reference articles on best practices on how to structure the gem lib directory. Having been bitten by these issues before, I consider these really important because file load conflicts are very hard to fix from the outside.

* https://blog.codeship.com/exploring-structure-ruby-gems/
* http://weblog.rubyonrails.org/2009/9/1/gem-packaging-best-practices/

The directories `lib/cache`, `lib/engine`, and `lib/exceptions` would need to be in `lib/splitcient-rb/...` to avoid conflicts. Good news is that each file has the proper module namespace, so a simple git mv for each of these directories followed by changes to paths in `sliptclient-rb.rb` should be sufficient.

### File Namespace

The other issue I see is that `lib/splitclient-rb_utilities.rb` defines a top level `Utilities` constant. This file name is OK since it is prefixed with the gem name, however, that module name is very ambiguous. Suggest changing the contents to use the `SplitIoClient::Utilities` namespace and making changes in the code to remove the `::` in places and everything should work fine.

What do you think? Is this something that you can fix or would you like a PR for it?
Again, thanks for the great work in the gem.

**Comment by maksimf** [comment]
Hey Ken, thank you very much for the feedback, everything makes perfect sense. I'll fix these issues very soon.

**Comment by maksimf** [comment]
@metaskills It's done 🎆
