### ISSUE TITLE
HTTP requests failing when faraday_middleware version < 0.10

### ISSUE THREAD

**Issue by mvpgomes** [splitio/ruby-client#158]
While configuring `splitclient-rb` for an existing application, I've bootstrap `SplitIoClient` following the available documention:

```ruby
require 'splitclient-rb'

options = {block_until_ready: 3}
split_factory = SplitIoClient::SplitFactoryBuilder.build("YOUR_API_KEY", options)
```
when instatiating the client I'm getting the following error:

```
ERROR -- : Failed to make a http request
INFO -- : Starting metrics service
ERROR -- : [splitclient-rb] Unexpected exception in store_splits: #<NoMethodError: undefined method `[]' for nil:NilClass> undefined method `[]' for nil:NilClass
	/bundle/gems/splitclient-rb-4.1.0/lib/cache/stores/split_store.rb:45:in `store_splits'
	/bundle/gems/splitclient-rb-4.1.0/lib/cache/stores/split_store.rb:35:in `block (2 levels) in splits_thread'
	/bundle/gems/splitclient-rb-4.1.0/lib/cache/stores/split_store.rb:34:in `loop'
	/bundle/gems/splitclient-rb-4.1.0/lib/cache/stores/split_store.rb:34:in `block in splits_thread'
INFO -- : Starting impressions service
WARN -- : uninitialized constant FaradayMiddleware::Gzip
```
If you look at the last line of the log, a warning is raised by `Faraday` saying that it doesn't know what is `FaradayMiddleware::Gzip`. **NOTE:** if you don't provide `options` to ` SplitIoClient::SplitFactoryBuilder.build`, when instantiating the client the request get stuck and we need to manually terminate the application execution.

After looking at `https://github.com/splitio/ruby-client/blob/master/lib/engine/api/client.rb#L10`, I saw that we are instantiating `Faraday` with `FaradayMiddleware::Gzip`, which is a dependency defined in `faraday_middleware` gem.

After digging my code I discovered that I already have installed `faraday_middleware` in version `0.9.2`. The issue is that  `FaradayMiddleware::Gzip` is only available from version `>= 0.10` https://github.com/lostisland/faraday_middleware/releases/tag/v0.10.0.

However, the currently `.gemspec` is not specifying a minor version for `faraday_middleware`, and if you already have a version installed, the gem will use that one, not matter which is the version of the installed gem. I will open a small PR to update `.gemspec` to specify a minor version for `faraday_middleware` as soon as possible 😄

**Comment by maksimf** [comment]
@mvpgomes thank you for this! I've submitter a PR: https://github.com/splitio/ruby-client/pull/160

**Comment by mvpgomes** [comment]
@maksimf thank you, already created a PR too #159 💃

**Comment by maksimf** [comment]
@mvpgomes ok, I'll let you steal my thunder this time :D
But please, target `development` branch

**Comment by metaskills** [comment]
At CustomInk we have quite a few applications that are in debt with Faraday pegged at `~> 0.8`. Most of our newer internal client gems test Faraday from that version up to `0.11` IIRC using the [Appraisal gem](https://github.com/thoughtbot/appraisal). Given that, two questions:

* Is there a version of this gem that can use an older Faraday gem?
* If not, is there any appetite to building this gem in such a way that works and is test with older Faraday gems?

**Comment by maksimf** [comment]
Let me investigate on that

**Comment by maksimf** [comment]
@metaskills After some research I've figured that we can't use `faraday_middleware` at `0.8` now, because we need `FaradayMiddleware::Gzip`. I think I'll find the solution how to deal with it though. I'll keep you posted here

**Comment by metaskills** [comment]
> because we need FaradayMiddleware::Gzip

Is that true? I was looking at the source (https://github.com/lostisland/faraday_middleware/blob/master/lib/faraday_middleware/gzip.rb) and it has comments like the following:

```
# This middleware is NOT necessary when these adapters are used:
# - net_http on Ruby 1.9+
# - net_http_persistent on Ruby 2.0+
# - em_http
```

**Comment by maksimf** [comment]
I've seen this as well, but no, it doesn't work without it
чт, 13 июля 2017 г. в 17:39, Ken Collins <notifications@github.com>:

**Comment by maksimf** [comment]
Hey @metaskills! I got rid of `faraday_middleware` completely and now we depend on faraday >= 0.8, so you should be fine, please confirm

**Comment by metaskills** [comment]
I can confirm that we can now bundle the latest 4.2.0 to our legacy application(s).

**Comment by maksimf** [comment]
Awesome!
