### ISSUE TITLE
JSON Gem Dep

### ISSUE THREAD

**Issue by metaskills** [splitio/ruby-client#163]
Trying to move forward on bundling this gem and hitting issues. I noticed there is a twiddle wakka dep for the JSON gem to `~> 1.8`. Checking the released for the gem does show recent updates for that version.

https://rubygems.org/gems/json/versions

I can explore setting `~> 1.8` in my Rails v5 app's Gemfile, but is there a reason we are locked down to 1.8? Can the dep be open ended or `>= 1.8` or something?

**Comment by maksimf** [comment]
Hey @metaskills! This is just a typo, sorry about that, I've already pushed the fix, check out `development` please

**Comment by metaskills** [comment]
Thanks!

**Comment by maksimf** [comment]
Thank you for reporting these, it's really helpful!
