### ISSUE TITLE
Redis Availability

### ISSUE THREAD

**Issue by metaskills** [splitio/ruby-client#180]
When we tested Split.io in `standalone` mode, I believe Redis going down caused `get_treatment` to not raise exceptions and return excluded. I could be wrong about this because as of now, we run the Go synchronizer and hence the Ruby apps are in `consumer` mode. Under this mode when the Redis connection goes down, any page that uses `get_treatment` will error out.

Our wrapper gem solves this by rescuing `Redis::BaseError` and returning `SplitIoClient::Engine::Models::Treatment::CONTROL`. To be fair, we never really had Redis go down and we do have our Split Redis AWS instance setup in such a way that we feel pretty confident about it being there for us. That said, just wanted to share this pattern and ask if there was anything more we could do on our end. Thanks in advance!

**Comment by adilaijaz** [comment]
Thanks for flagging. That's not expected behavior. We are looking into this. Will keep you posted.

**Comment by patricioe** [comment]
Ken,

This PR should address the issue: https://github.com/splitio/ruby-client/pull/184

Release coming soon but I wanted to let you know in case you need to test/use it immediately.

**Comment by patricioe** [comment]
Ken,

The version 4.3.1 should fix the problem you ran into. I'll go ahead and close this ticket. Let us know if we can help with anything else.

**Comment by metaskills** [comment]
Thanks! Confirmed this does indeed work.
