### ISSUE TITLE
Attributes Ignored in get_treatment

### ISSUE THREAD

**Issue by smythey21** [splitio/ruby-client#183]
I noticed that no matter what attributes I was passing into `get_treatment`, my dashboard in Split.io logged the request but without attributes.

```
client.get_treatment("SOME_USER", "SOME_TEST", { random_attribute: "blah" })
```

<img width="294" alt="screen shot 2017-11-10 at 9 47 08 am" src="https://user-images.githubusercontent.com/7821161/32668922-e48b15fa-c60c-11e7-9cf4-822a4866baa5.png">

Looks like attributes are completely ignore here: https://github.com/splitio/ruby-client/blob/master/lib/splitclient-rb/clients/localhost_split_client.rb#L44-L56

**Comment by patricioe** [comment]
Hi Kevin,

Thanks for reaching out. Unfortunately, we used the word attributes for both `get_treatment` calls and for those attributes of the traffic you pointed out. This is on us and we are working towards preventing that confusing.

The reason why we don't autopopulate those attributes from the get_treatment calls is to keep the privacy of that information within your infrastructure and we only use them to evaluate the treatment to return.

If you do want to send us that information, please refer to our public API and wrapper clients here: https://docs.split.io/docs/identifying-customers

**Comment by smythey21** [comment]
Thanks @patricioe. I was reading the documentation you pointed to me to, and it sounded like I could get attributes with `client.attributes.list` and save then with `client.attributes.save` but I'm getting an error from that:

```
irb(main):005:0> client.attributes
NoMethodError: undefined method `attributes' for #<SplitIoClient::SplitClient:0x007f8d1415ecc8>
	from (irb):5
```

**Comment by patricioe** [comment]
Kevin,

Are you using the correct gem? `gem 'splitapi-rb'` 
Notice that it's different gem than the one used in the ruby client for the SDK.

**Comment by smythey21** [comment]
No I'm using `splitclient-rb (4.3.0)`.  Am I supposed to use `splitapi-rb`? The docs seem to say `splitclient-rb` is the right gem.

**Comment by patricioe** [comment]
Yes, you need to use that other gem.


It is specified here: 
![image](https://user-images.githubusercontent.com/250893/32676247-c11a729e-c60e-11e7-946e-a274c6751514.png)

**Comment by patricioe** [comment]
@smythey21 let us know if we can help with anything else. Feel free to reach out to support@ at any time.
