### ISSUE TITLE
JRuby support

### ISSUE THREAD

**Issue by tjsousa** [splitio/ruby-client#191]
I'm using the ruby client gem in one of our projects at Talkdesk and when running on JRuby an error is thrown due to a dependency using C extensions:

Just wondering if this is a known limitation and if there is value in being compatible with JRuby?

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/usr/local/bundle/gems/digest-murmurhash-1.1.1/ext/digest/murmurhash
/opt/jruby/bin/jruby -r ./siteconf20180209-5-1h8ixdd.rb extconf.rb
creating Makefile

current directory:
/usr/local/bundle/gems/digest-murmurhash-1.1.1/ext/digest/murmurhash
make "DESTDIR=" clean

current directory:
/usr/local/bundle/gems/digest-murmurhash-1.1.1/ext/digest/murmurhash
make "DESTDIR="
make: *** No rule to make target '/opt/jruby/lib/ruby/include/ruby/ruby.h',
needed by 'neutral2.o'.  Stop.

make failed, exit code 2

Gem files will remain installed in
/usr/local/bundle/gems/digest-murmurhash-1.1.1 for inspection.
```

**Comment by SenhorCastor** [comment]
Hi tjsousa, thanks for reaching out.

Currently we do not support JRuby - we used a library that is in C -. Our team is aware of this and we will work on making it compatible with JRuby in our next sprint.

I will keep this open and comment once we have an update

Thanks
Fernando

**Comment by goldensun8891** [comment]
@tjsousa we have a RC branch that is now available to address this if you'd like to use it as a dry run?

**Comment by patricioe** [comment]
@tjsousa ping.

Would it be possible for you to try this release candidate?

**Comment by SenhorCastor** [comment]
Closing this, we have a JRuby gem available.

If you have any issues dont hesitate to contact
