### ISSUE TITLE
cache_ttl in consumer mode

### ISSUE THREAD

**Issue by svyandun** [splitio/ruby-client#262]
https://github.com/splitio/ruby-client/blame/master/Detailed-README.md#L372

The detailed documentation is a bit confusing. It mentions a `memory` cache when using Redis. Why would a consumer use a `memory` cache if it's already using Redis?

Similarly, why would a `cache_ttl` exists if the consumer is only reading the cache? I would assume those option should live in the `synchronizer`, no?

**Comment by patricioe** [comment]
Hey,

Just to close the loop since we responded via private support channel. This is an internal setting and will be removed shortly for the Detailed README file.

Closing this now.
