### ISSUE TITLE
`fix_latencies` is running every restart by each app server, affecting Redis performance

### ISSUE THREAD

**Issue by hopfish** [splitio/ruby-client#284]
Hello!

We have a Split setup using the Ruby client in consumer mode, with Redis to communicate with the split synchronizer. The `fix_latencies` fix [found here](https://github.com/splitio/ruby-client/blob/47f0033c678f037fca0835b7f44b183374de6aec/lib/splitclient-rb/cache/repositories/metrics/redis_repository.rb#L69) has the effect of consuming a ton of Redis resources. This is run on each restart of the servers, and on each app server where we use the split gem. With a large number of app servers, and a shared Redis instance, the repeated `scan` commands are causing Redis performance issues.

Could we have an option to disable the fix? It has already been run, and doesn't need to be re-run each restart. 

Thanks!

**Comment by NicoZelaya** [comment]
Hi @hopfish ! 

Our sincere apologies for the issues this might have caused. We'll look into it and I'll get back to you with our plan, but definitely makes sense to not run it several times.

Thank you very much for reporting this!

I'll keep you posted,
Nico.

**Comment by NicoZelaya** [comment]
Hello again @hopfish ! We're already working on a fix for this issue. First time it runs we'll mark it as such and afterwards it won't run again. 

Looking at sending it for testing to our staging environment soon, if all goes well it should be released as stable this week.

I'll keep updating you here. 

Thanks for your patience!
Nico.

Nico.

**Comment by sanzmauro** [comment]
Hi @hopfish !

We released 7.0.2 with the fix. Again our sincere apologies for the issues and please let us know if you have any concerns after upgrading the sdk.

Kindest regards,
Mauro.

**Comment by hopfish** [comment]
Great, thanks for the speedy response! We will upgrade and let you know if there are any more issues.
