### ISSUE TITLE
Redis.exists? deprecation warning from redis v4.2.2

### ISSUE THREAD

**Issue by grhansen** [splitio/ruby-client#342]
We recently upgraded some components in our application and are running 7.0.3 of your gem. 

We're using a `redis-namespace` gem which has upgraded our `redis` gem to version 4.2.2. I see you are also including the redis gem in your gem-spec: https://github.com/splitio/ruby-client/blob/master/splitclient-rb.gemspec#L58

We're now getting a deprecation warning on this line of code in your gem: https://github.com/splitio/ruby-client/blob/master/lib/splitclient-rb/cache/adapters/redis_adapter.rb#L38

I noticed in your test files that you're already appending the `?` so it won't be an issue there, but you'll need to make adjustment to use the `?` in your code before your gem can upgrade to `redis` 4.3.

The change is obviously very quick and you already have test coverage for the `exists` method. We'd love to resolve the deprecation warning to clean up our log file output. Would you mind making the change or I'm happy to fork and submit a PR if you'd prefer I submit the change for consideration.

Let me know.

**Comment by sanzmauro** [comment]
Hi @grhansen, Thanks for reporting this!

We are working on that. We will release `7.2.1` with this gem upgrade the next week.

We'll keep you posted on the work we do. Thank you again for the report.

Regards, 
Mauro

**Comment by grhansen** [comment]
:+1:

**Comment by sanzmauro** [comment]
Hi @grhansen `7.2.1` released. 

I will close the issue, let me know if anything comes up!

Regards,
Mauro
