### ISSUE TITLE
Quickstart: SDK Setup code does not work

### ISSUE THREAD

**Issue by MarcoMartins86** [splitio/ruby-client#351]
I am new to Ruby and to Split, although, the code that was generated on the Quickstart: SDK Setup has an issue. The code is below:

```
require 'splitclient-rb'

options = {
  block_until_ready: 10
}

factory = SplitIoClient::SplitFactoryBuilder.build(API_KEY, options)
split_client = factory.client

treatment = split_client.get_treatment('CUSTOMER_ID', 'test')

if treatment == 'on'
  puts 'I am on'
elsif treatment == 'off'
  puts 'I am off'
else
  puts 'Control'
end
```

Independently of the `block_until_ready` value, I have increased it to 120, I always got **ERROR -- : get_treatment: the SDK is not ready, the operation cannot be executed**.

Solved it with `split_client.block_until_ready` but then I remove the instruction and afterward, I did a while loop to check how much time it would take to establish the connection:
```
while 1 do
treatment = split_client.get_treatment('CUSTOMER_ID', 'test')
if treatment == 'on'
  puts 'I am on'
elsif treatment == 'off'
  puts 'I am off'
else
  puts 'Control'
end
sleep(1)
end
```
And it would work after 1s, so I conclude that `options` with the `block_until_ready` is doing nothing.
Now I am not sure if it is a bug or if it is only the generated tutorial code that is wrong.
I am using splitclient-rb (7.2.2).

**Comment by chillaq** [comment]
Hi @MarcoMartins86, the SDK needs to download information from Split cloud before it is ready to calculate treatments, the split_client.block_until_ready method will hold the current thread until the download is completed.

The option block_until_ready is simply a timeout you set that will raise exception if the SDK is not ready within that time, and allow you to run other startup code.

The SDK will continue to download the cache regardless if the timeout has reached.

Hope that helps.

Thanks
Bilal

**Comment by chillaq** [comment]
Hi @MarcoMartins86, Correction, the config option block_until_ready is deprecated, you can pass the time out needed to the split_client.block_until_ready() method as below:
split_client.block_until_ready(5). # timeout is set to 5 seconds

Thanks
Bilal

**Comment by MarcoMartins86** [comment]
Hi Bilal, thank you for replying, so my point is maybe you should update the example code so that other newbies like me don't lose some time understanding the root cause for the error. The tutorial should work out of the box from my point of view.

**Comment by chillaq** [comment]
Hi @MarcoMartins86, I do agree, will make sure to fix the code samples.

Thanks
Bilal
