### ISSUE TITLE
7.2.3 performance issues

### ISSUE THREAD

**Issue by mkrisher** [splitio/ruby-client#360]
We've noticed after upgrading from 7.2.2 to 7.2.3 we're experiencing performance issues. Our test suite grinds to a halt after a few seconds. Memory leak maybe?

I've forked and can take a closer look at the diff between the versions but wanted to open an issue before I did.

**Comment by chillaq** [comment]
Hi @mkrisher , Thanks for the info, could you elaborate more on which SDK calls have a performance hit? Can you enable debug logging for the SDK as well?

Thanks
Bilal

**Comment by chillaq** [comment]
Hi @mkrisher , let me know if you still need any help in this issue.

Thanks
Bilal

**Comment by mkrisher** [comment]
I haven't had time to revisit this. I'll close it for now and open a new ticket when I revisit and everything is fresh.

**Comment by mkrisher** [comment]
FWIW, I'm no longer seeing the issue with 7.3.1.
