### ISSUE TITLE
High CPU usage on wrong split key

### ISSUE THREAD

**Issue by rasa-silva** [splitio/ruby-client#363]
While debugging an incident, we noticed that https://github.com/splitio/ruby-client/blob/87b94d0b965c50fd4dd830b3c2d0bc38e8149fad/lib/splitclient-rb/cache/fetchers/segment_fetcher.rb#L69 is doing an early loop exit without delaying which causes too much CPU usage when the split key is invalid.

**Comment by chillaq** [comment]
Hi @rasa-silva, thanks for the info, which Ruby SDK version you are using? I will repro locally.

Thanks
Bilal

**Comment by rasa-silva** [comment]
7.2.3

**Comment by chillaq** [comment]
Thanks @rasa-silva, I see the issue, cpu usage below while SDK retry to connect.

 top -l 0 | grep ruby
57749  ruby             0.0  00:01.03 9/1   0   30+    20M+  
57749  ruby             57.6 00:01.86 9/1   0   30     20M   
57749  ruby             98.2 00:02.89 9/1   0   30     20M   
57749  ruby             99.2 00:03.93 9/1   0   30     20M   
57749  ruby             99.1 00:04.97 9/1   0   30     20M   
57749  ruby             98.9 00:06.01 9/1   0   30     20M+  
57749  ruby             99.0 00:07.05 9/1   0   30     20M   
57749  ruby             98.9 00:08.09 9/1   0   30     20M   
57749  ruby             97.9 00:09.12 9/1   0   30     20M+  
57749  ruby             98.1 00:10.16 9/1   0   30     20M   
57749  ruby             97.2 00:11.18 9/1   0   30     20M   
57749  ruby             99.2 00:12.28 9/1   0   30     20M   
57749  ruby             98.7 00:13.32 9/1   0   30     20M+  
57749  ruby             98.3 00:14.35 9/1   0   30     20M   
57749  ruby             98.7 00:15.38 8/1   0   29-    20M-  
57749  ruby             98.2 00:16.41 8/1   0   29     21M+  
57749  ruby             98.7 00:17.45 7/1   0   28-    21M+  
57749  ruby             98.5 00:18.49 5/1   0   26-    21M+

**Comment by chillaq** [comment]
Hi @rasa-silva , we released ruby SDK 7.3.0 that contains a fix for this issue.

Thanks
Bilal
