### ISSUE TITLE
Update Rake version to support development on Ruby 3

### ISSUE THREAD

**Issue by scytherswings** [splitio/ruby-client#423]
Rake 13.0.x introduces fixes in PR [#326](https://github.com/ruby/rake/pull/326) which fix kwargs behavior which is currently broken when trying to develop locally in this project on newer Ruby versions.

**Comment by chillaq** [comment]
Thanks @scytherswings , will check with the team.

**Comment by sanzmauro** [comment]
Hi @scytherswings  , we released ruby SDK `8.0.0` that contains a fix for this issue.

I will close the issue, let me know if anything comes up!

Regards,
Mauro
