### ISSUE TITLE
Update CI to target non-EOL Ruby

### ISSUE THREAD

**Issue by scytherswings** [splitio/ruby-client#425]
It appears CI is running against Ruby 2.5 https://github.com/splitio/ruby-client/blame/master/.github/workflows/ci.yml#L26 which is EOL as of 2021. https://www.ruby-lang.org/en/downloads/branches/

**Comment by chillaq** [comment]
Thanks @scytherswings, checking with the team.

**Comment by chillaq** [comment]
Hi @scytherswings , I have a response for you:  Thanks for the info, we will make some changes on the CI at a later time and we will include reviewing Ruby versions used as part of this process.
