### ISSUE TITLE
Split logger errors

### ISSUE THREAD

**Issue by so-ravindra** [splitio/ruby-client#426]
I am receiving below error in my logger frequently: 

Splitio: Error during connecting to streaming.split.io. Error: #<Socketry::TimeoutError: connection to 18.66.248.99:443 timed out>

Splitio: #<Socketry::TimeoutError: read timed out after 70 seconds>

Splitio: #<RuntimeError: eof exception>

Are these any concern?

**Comment by chillaq** [comment]
Hi @so-ravindra, the streaming connection support updating the SDK cache on demand, this is a websocket connection, if your environment block websocket connections to outside, you will see these errors.
The SDK will switch to polling mechanism to sync the cache, so no impact on SDK functionality here.

Hope that helps.

**Comment by so-ravindra** [comment]
Thanks
