### ISSUE TITLE
Faraday 2.0+ compatibility

### ISSUE THREAD

**Issue by malachewhiz** [splitio/ruby-client#436]
Can you tell if or when you will support faraday version 2.0 and above? This limitation is preventing us from evaluating Split's services.

**Comment by chillaq** [comment]
Hi @malachewhiz, checking with the team.

**Comment by sanzmauro** [comment]
Hi @malachewhiz, I released a [rc](https://rubygems.org/gems/splitclient-rb/versions/8.0.1.pre.rc1-java) supporting faraday 2.0+.

We are testing the rc from our side and if all is good we will release a stable version next week. Feel free to use it if you want. 

Regards,
Mauro

**Comment by malachewhiz** [comment]
Thanks a lot! I'll try out the rc as soon as I can.

**Comment by malachewhiz** [comment]
Working as expected. Thanks again! 

Closing the issue.

**Comment by sanzmauro** [comment]
Hi @malachewhiz ,

We released the [stable version](https://rubygems.org/gems/splitclient-rb/versions/8.0.1).

Regards,
Mauro
