### ISSUE TITLE
Splitio: #IOError: stream closed in another thread

### ISSUE THREAD

**Issue by sonupandey228** [splitio/ruby-client#481]
I am encountering the following error consistently in the logger:
Splitio: #<IOError: stream closed in another thread>

**Comment by agustinona** [comment]
Hi @sonupandey228, could you specify which version of the SDK are you running? What stack are you running the SDK on? If you are running a multiprocess web server, are you running the recommended configs per our docs? https://help.split.io/hc/en-us/articles/360020673251-Ruby-SDK#sdk-server-compatibility

If you have a sample project for us to reproduce the issue and/or can produce debug logs (see: https://help.split.io/hc/en-us/articles/360020673251-Ruby-SDK#logging), please do share those with us. You can also send them to support@split.io to open a support ticket if you prefer not to share here.

**Comment by sonupandey228** [comment]
Hi @agustinona Thanks for answer, Yes we are running recommended configs as per docs. https://help.split.io/hc/en-us/articles/360020673251-Ruby-SDK#sdk-server-compatibility

I am running SDK version 8.1.2 and running on ruby on rails. I am using ruby version 3.1.4 and rails 7.0.5.

**Comment by sonupandey228** [comment]
Here is a sample project in which `Splitio: #<IOError: stream closed in another thread>` can be reproduce. https://github.com/scheduleonce/split-client-demo/tree/main

It is running on docker image on kubernetes.

Attached image of error log receiving consistently.
![image](https://github.com/splitio/ruby-client/assets/102135494/b71a166b-0e8f-493e-8326-af0153cc9cd9)

**Comment by agustinona** [comment]
Thank you @sonupandey228 

How often are these messages being logged?

What SDK version are you on? Based on your example it seems you are running 8.1.2. In 8.2.0 an improvement to the streaming connection handling was introduced which could have an impact on this. Could you try that version and let me know if the problem persists?

**Comment by sonupandey228** [comment]
Yes updating version to 8.2 resolved the issue. Thanks

**Comment by sonupandey228** [comment]
Yes updating version to 8.2 resolved the issue. Thanks
