### ISSUE TITLE
Error during a parsing event

### ISSUE THREAD

**Issue by counterbeing** [splitio/ruby-client#515]
I'm using your service and the 7.3.4 gem version. I'm running into this error when updates come back:

```
Error during parsing a event: #<JSON::ParserError: unexpected token at 'data:
{"id":"xbWhZupEwC:0:0","timestamp":1711579820508,"clientId":"pri:MzU2Nzc3Mzc4NQ==","channel":"MjYyNDc3NDY0OQ==_NDAwMTc1NDgxNw==_splits","data":"{\"type\":\"SPLIT_UPDATE\",\"changeNumber\":1711579819987,\"pcn\":1711579723688,\"c\":2,\"d\":\"eJy8kk2L2zwcxL+KmbO8WLbjF93Cs8vT0DSBTdpSgimyLSdiZTnIMiUN/u5FSTabpqXQS2/S6P8y/o2PsIY3jazWh71Y8FaAgetOH9pu6EEgazA0eZTWSRr4ZRnkPqVC+FlEGz9LYtrENEuSPAaBPrc/LhfLZz+Lcr/uNLfC7/dKWpDXTVOluopb2WkwGgS/0VdC1GA0m+R5mKRJTNCfFJ/GYZYmNM4Iesvt0INh+t969ukJBC9SKVfVcNULglo0fFB2bQS3rdAWDJ0GQbXjeisWQ1sKA0ZTSidpntE8z1K3x/Zgm4KAq20HFhJUnW7kdjAnZz3YcTxptbzcN8e3q4MIhuflfL78uAZBy221E+Z/0w17MFfZllK7xZguHt8KznNexGEllKhsZ1zxTTJ3qXBrjSwH6/Rm0LXhshcG43Xepefzu9n6aT5bOStabLlruOD5tpNWKNnbD+eOR265W3rVwTagYQSCMKDRZAICSpM8Px2iKI7D10OEYhyLkWDPjb3BYu/R9/K7OGU+krvXprk+B2NBoHgp1E8f50ntOVvehoYR8c6eiPfw8FDAjfvHGfyCejqff33/9GV1T/ovwPwRi6N2A+byd3tmUAJjMf4IAAD//4H5OTc=\"}","encoding":"json"}'>
```
This is when running in local dev. I'm not sure if these issues are happening elsewhere.

Upgrading to the latest gem isn't much of an option for us. We're trying to use Split to help us migrate off of this old project.

Thanks!

**Comment by kleinjoshuaa** [comment]
Hi, 
 
This is a [fixed bug](https://github.com/splitio/ruby-client/issues/511) in our most recent SDK that affected the streaming service. You might still be able to get Split to work if you pass in the option to disable the streaming service and have the SDK fall back to polling 
 ```
options = {streaming_enabled: false}
 ```

Note that, while we do our best to be helpful, a 2 year old SDK is technically outside of our [SDK support policy](https://help.split.io/hc/en-us/articles/360038143771-SDK-versioning-policy).
